[workspace]
members = [
    "common",
    "trace",
    "trace_proc_macro",
    "trace_viewer_app",
    "tyro_lang",
    "render",
    # "render_opengl",

    "editor",
    "nodes_engine",
    "nodes_editor",

    "playground",
]
