[package]
name = "render-vulkan"
version = "0.1.0"
authors = ["Ivan Pleshkov <pleshkov.ivan@gmail.com>"]
edition = "2018"

[dependencies]
render = { path = "../render" }
# vulkano = "0.14.0"
ash = "0.29.0"
log = "0.4"
