[package]
name = "render-vulkan"
version = "0.1.0"
authors = ["Ivan Pleshkov <pleshkov.ivan@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
render = { path = "../render" }
ash = "0.29.0"
log = "0.4"
semver = "0.7.0"
