[package]
name = "tyro_lang"
version = "0.1.0"
authors = ["Ivan Pleshkov <pleshkov.ivan@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
log = "0.4"
fern = "0.5"
nalgebra = "0.21.1"
semver = "0.9"
pest = "2.1.0"
pest_derive = "2.1.0"
