[package]
name = "core"
version = "0.1.0"
authors = ["Ivan Pleshkov <Ivan.Pleshkov@darkmatter.ae>"]
edition = "2018"

[dependencies]
log = "0.4"
optional = "0.5.0"
num-traits = "0.2.8"
cgmath = "0.17.0"
