[package]
name = "editor"
version = "0.1.0"
authors = ["Ivan Pleshkov <Ivan.Pleshkov@darkmatter.ae>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
log = "0.4"
fern = "0.5.8"
chrono = "0.4.9"
nalgebra = "0.21.1"
optional = "0.5.0"
num-traits = "0.2.8"
